[package]
name = "xtask"
version = "1.0.0"
authors = ["Cliff L. Biffle <cliff@oxide.computer>", "Steve Klabnik <steve.klabnik@oxide.computer>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.15"

# for package
serde = { version = "1.0.114", features = ["derive"] }
toml = "0.5.6"
indexmap = { version = "1.4.0", features = ["serde-1"] }
srec = "0.2.0"
goblin = { version = "0.2.3", features = ["std", "elf32", "endian_fd"] }
serde_json = "1.0.56"
path-slash = "0.1.3"
ctrlc = "3.1.5"
zip = "0.5.6"
abi = { path = "../abi" }
nxp-structs = { path = "../nxp-structs" }
byteorder = "1.3.4"
# For NXP signing
openssl = "0.10.30"
bitfield = "0.13.2"
bincode = "1.3.1"
packed_struct = "0.3.0"
packed_struct_codegen = "0.3.0"
