[package]
name = "drv-lpc55-rng-core"
version = "0.1.0"
authors = ["Laura Abbott <laura@oxide.computer>",]
edition = "2018"

[features]
default = ["standalone", "rng"]
standalone = []
rng = ["chacha20/rng"]

[dependencies]
zerocopy = "0.3.0"
lpc55-pac = "0.1.0"
num-traits = { version = "0.2.12", default-features = false }
rand_core = { version = "0.5.0", default-features = false }
chacha20 = "0.6.0"

# a target for `cargo xtask check`
[package.metadata.build]
target = "thumbv8m.main-none-eabihf"

