name = "demo-100fx"
target = "thumbv7em-none-eabihf"
board = "gemini-bu-1"
stacksize = 1024

[kernel]
path = "."
name = "demo-100fx"
requires = {flash = 32768, ram = 4096}
#
# For the kernel (and for any task that logs), we are required to enable
# either "itm" (denoting logging/panicking via ARM's Instrumentation Trace
# Macrocell) or "semihosting" (denoting logging/panicking via ARM
# semihosting).  We are biased to ITM because semihosting is excruciatingly
# slow (it is breakpoint based) and has an undesirable failure mode if logging
# output is generated and debugger is not attached (namely, the target stops).
# If one does choose to change this to semihosting for purposes of
# development, be sure to also change it in every task of interest.
#
features = ["itm"]

[supervisor]
notification = 1

# Flash sections are mapped into flash bank 1 (of 2).
[outputs.flash]
address = 0x08000000
size = 1048576
read = true
execute = true

# RAM sections are currently mapped into DTCM, a small but fast SRAM.
[outputs.ram]
address = 0x20000000
size = 131072
read = true
write = true
execute = false  # let's assume XN until proven otherwise

# Network buffers are placed in sram1, which is directly accessible by the
# Ethernet MAC.
[outputs.sram1]
address = 0x30000000
size = 0x20000
read = true
write = true
dma = true

[tasks.jefe]
path = "../task-jefe"
name = "task-jefe"
priority = 0
requires = {flash = 16384, ram = 1024}
start = true
features = ["itm"]
stacksize = 1000

[tasks.rcc_driver]
path = "../drv/stm32h7-rcc"
name = "drv-stm32h7-rcc"
priority = 1
requires = {flash = 8192, ram = 1024}
uses = ["rcc"]
start = true

[tasks.gpio_driver]
path = "../drv/stm32h7-gpio"
name = "drv-stm32h7-gpio"
priority = 2
requires = {flash = 8192, ram = 1024}
uses = ["gpios1", "gpios2", "gpios3"]
start = true

[tasks.spi_driver]
path = "../drv/stm32h7-spi-server"
name = "drv-stm32h7-spi-server"
priority = 2
requires = {flash = 16384, ram = 2048}
uses = ["spi2"]
start = true
interrupts = {36 = 1}
stacksize = 1000

[tasks.ethernet]
path = "../drv/stm32h7-eth"
name = "drv-stm32h7-eth"
features = ["h743", "itm"]
priority = 2
requires = {flash = 32768, ram = 2048, sram1 = 32768}
sections = {eth_bulk = "sram1"}
uses = ["eth", "eth_dma"]
start = true
interrupts = {61 = 1}

[tasks.demo_100fx]
path = "../task-demo-100fx"
name = "task-demo-100fx"
features = ["itm"]
priority = 3
requires = {flash = 16384, ram = 2048}
start = true

[tasks.user_leds]
path = "../drv/user-leds"
name = "drv-user-leds"
features = ["stm32h7"]
priority = 2
requires = {flash = 8192, ram = 1024}
start = true

[tasks.blink_status]
path = "../task-blink-status"
name = "task-blink-status"
priority = 4
requires = {flash = 8192, ram = 512}
stacksize = 512
start = true

[tasks.idle]
path = "../task-idle"
name = "task-idle"
priority = 5
requires = {flash = 256, ram = 256}
stacksize = 256
start = true

[peripherals.rcc]
address = 0x58024400
size = 1024

[peripherals.gpios1]
address = 0x58020000
size = 0x2000

[peripherals.gpios2]
address = 0x58022000
size = 0x0800

[peripherals.gpios3]
address = 0x58022800
size = 0x0400

[peripherals.usart1]
address = 0x40004800
size = 1024

[peripherals.spi2]
address = 0x40003800
size = 1024

[peripherals.eth]
address = 0x40028000
size = 0x1000

[peripherals.eth_dma]
address = 0x40029000
size = 0x400
