[package]
name = "drv-lpc55-aes"
version = "0.1.0"
authors = ["Laura Abbott <laura@oxide.computer>"]
edition = "2018"

[dependencies]
userlib = {path = "../../userlib"}
zerocopy = "0.3.0"
lpc55-pac = "0.1.0"
cortex-m-semihosting = "0.3.3"
num-traits = {version = "0.2", default-features = false}
cortex-m = "0.6.0"

[features]
default = ["standalone"]
standalone = []

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "drv-lpc55-aes"
test = false
bench = false
