[package]
name = "drv-spiflash-api"
version = "0.1.0"
authors = ["Bryan Cantrill <bryan@oxide.computer>"]
edition = "2018"

[dependencies]
userlib = {path = "../../userlib"}
ringbuf = {path = "../../ringbuf"}
abi = {path = "../../abi"}
#drv-stm32h7-qspi = {path = "../stm32h7-qspi"}
zerocopy = "0.3.0"
byteorder = { version = "1.3.4", default-features = false }
num-traits = { version = "0.2.12", default-features = false }

# a target for `cargo xtask check`
[package.metadata.build]
target = "thumbv7em-none-eabihf"

[features]
standalone = []

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[lib]
test = false
bench = false
