[package]
name = "drv-stm32h7-eth"
version = "0.1.0"
authors = ["Cliff L. Biffle <cliff@oxide.computer>"]
edition = "2018"

[features]
default = []
with-smoltcp = ["smoltcp"]

[dependencies]
cortex-m = "0.7"
userlib = {path = "../../userlib"}
stm32h7 = {version = "0.13", features = ["stm32h743"]}

[dependencies.smoltcp]
optional = true
version = "0.7.1"
default-features = false

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[lib]
test = false
bench = false

[package.metadata.build]
target = "thumbv7em-none-eabihf"
