[package]
name = "drv-stm32h7-eth"
version = "0.1.0"
authors = ["Cliff L. Biffle <cliff@oxide.computer>"]
edition = "2018"

[dependencies]
userlib = {path = "../../userlib"}

[build-dependencies]
build-util = {path = "../../build-util"}

[features]
default = ["standalone"]
standalone = []

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "drv-stm32h7-eth"
test = false
bench = false

[package.metadata.build]
target = "thumbv7em-none-eabihf"
