[package]
name = "userlib"
version = "0.1.0"
authors = ["Cliff L. Biffle <cliff@oxide.computer>"]
edition = "2018"

[features]
default = ["panic-messages"]
panic-messages = []
log-itm = []
log-semihosting = []

[dependencies]
abi = {path = "../abi"}
r0 = "1.0"
serde = {version = "1", default-features = false}
ssmarshal = {version = "1", default-features = false}
zerocopy = "0.3"

[lib]
test = false
bench = false

[build-dependencies]
serde = "1"
serde_json = "1"
